cpq:
  username: "![KM81PSjB1yWKQiNpmeJfnc0mRraeXXmQ6lGJfs6399c=]"
  password: "![BJgOsL7+CkTXmM3IGI+SPQ==]"
  token: "![6E6x8gYoxA5OmF4L2ES/5IUROGDJrkxPc2FIjIdoKDY=]"
snowflake:
  username: "![ruVIg0QegpLklMGMYjJXYhyDSNs7tvOo]"
  password: "![rhu3buUH1b5Y3VvKuUAR8Q==]"
  accountName: "![cqUV44REXKA=]"
mq:
  client_id: "![oYH+7+3we6NiEciQeqRAYQ/GFExV4v61yAREJ55jj4nroG/2Kbds9A==]"
  client_secret: "![Kq18ltTFfVlxhMPi5LgntIUW0cMz8rKfTQg3UtsYrQ4MfWEzr7yYGQ==]"